server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: gestion-bibliotheque
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotheque
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect






